studentInfo/config/routes.rb
Rails.application.routes.draw do
  resources :infos
  get 'infos/index'
  get 'infos/show'
  get 'infos/new'
  get 'infos/create'
  get 'infos/edit'
  get 'infos/update'
  get 'infos/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

studentInfo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

studentInfo/app/models/info.rb
class Info < ApplicationRecord
  validates :name, :presence => true
  validates :email, :presence => true
  validates :password, :confirmation => true
  validates :password_confirmation, :presence => true
end

studentInfo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

studentInfo/app/controllers/infos_controller.rb
class InfosController < ApplicationController
  def index
    @infos = Info.all
    render :index
  end

  def show
    @info = Info.find(params[:id])
    render :show
  end

  def new
    @info = Info.new
    render :new
  end

  def create
    @info = Info.new(info_params)
    if @info.save
      redirect_to infos_path
    else
      render :new
    end
  end
  def edit
    @info = Info.find(params[:id])
    render :edit
  end

  def update
    @info = Info.find(params[:id])
    if @info.update(info_params)
      redirect_to infos_path
    else
      render :edit
    end
  end

  def destroy
    @info = Info.find(params[:id])
    @info.destroy
    redirect_to infos_path
  end
  private
  def info_params
    params.require(:info).permit(:name,:age,:email,:password,:password_confirmation,:bio)
  end
end

studentInfo/app/helpers/application_helper.rb
module ApplicationHelper
end

studentInfo/app/helpers/infos_helper.rb
module InfosHelper
end

studentInfo/app/views/infos/create.html.erb
<h1>Infos#create</h1>
<p>Find me in app/views/infos/create.html.erb</p>

studentInfo/app/views/infos/destroy.html.erb
<h1>Infos#destroy</h1>
<p>Find me in app/views/infos/destroy.html.erb</p>

studentInfo/app/views/infos/edit.html.erb
<h1 style="margin: 2% 40%">Infos edit</h1>

<%= render "layouts/form" %>

studentInfo/app/views/infos/index.html.erb
<h1 class="text-center mt-2 mb-5 text-success"> Infos </h1>
<p><%= link_to "login" %></p>
<% @infos.each do |post|%>
  <h2><%= link_to post.name, post %></h2>
  <p><%= link_to "Edit", edit_info_path(post) %> |
    <%= link_to "Delete", post,:data => {:confirm => "You sure?", :method => "delete"}  %></p>
  <hr>
<% end %>
<p><%= link_to "Add a new post", new_info_path %></p>

studentInfo/app/views/infos/new.html.erb
<h1 style="margin: 2% 40%">Infos new</h1>
<%= render "layouts/form" %>

studentInfo/app/views/infos/show.html.erb
<h1 style="margin: 2% 40%">Infos show</h1>
<h3><%= @info.name %></h3>
<p><%= @info.age %></p>
<p><%= @info.email %></p>
<p><%= @info.bio %></p>
<p><%= @info.password %></p>
<small><%= @info.created_at %></small>
<p><%= link_to "Return to Home", infos_path %></p>

studentInfo/app/views/infos/update.html.erb
<h1>Infos#update</h1>
<p>Find me in app/views/infos/update.html.erb</p>

studentInfo/app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li class="alert alert-danger"><%= message %></li>
    <% end %>
  </ul>
<% end %>

studentInfo/app/views/layouts/_form.html.erb
<%=render "layouts/errors", :object => @info %>

<%= form_for @info do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name , class:"form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :age %>
    <%= f.text_field :age , class:"form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email , class:"form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password , class:"form-control"%>
  </div>
  <div class="form-group">
    <%= f.label "password Confirmation" %>
    <%= f.password_field :password_confirmation , class:"form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :bio %>
    <%= f.text_area :bio , class:"form-control"%>
  </div>
  <div class="form-group">
   <%= f.submit "Add Now", class:"btn btn-success btn-lg" %>
  </div>
<% end %>

studentInfo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentInfo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>